version: '3.2'

services:
  api-test-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: >
      bash -c "set -x;
               cd /opt/api;
               while true; do python app.py; done;"
    container_name: ${APP_NAME}-api-test-api
    depends_on:
      - postgres-test-api
    environment:
      - APP_NAME=$APP_NAME
      - BUZZSUMO_API_KEY=$BUZZSUMO_API_KEY
      - COMMAND_NAME=$COMMAND_NAME
      - ENV=${ENV:-development}
      - GIT_TAG=$GIT_TAG
      - MODE=${MODE:-test-api}
      - OBJECT_STORAGE_URL=$OBJECT_STORAGE_URL
      - POSTGRES_URL=postgresql://${DB_NAME}_user:${DB_NAME}_password@postgres-test-api/${DB_NAME}
      - SCREEN_SHOT_MACHINE_KEY=$SCREEN_SHOT_MACHINE_KEY
      - TLD=$TLD
    networks:
      - db_test-api_nw
    volumes:
      - ./api:/opt/api

  postgres-test-api:
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    container_name: ${APP_NAME}-postgres-test-api
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_NAME}_password
      - POSTGRES_USER=${DB_NAME}_user
    image: postgres:10.1
    networks:
      - db_test-api_nw
    volumes:
      - "./docker_data_test-api/postgres:/var/lib/postgresql"

networks:
  db_test-api_nw:
    driver: bridge

volumes:
  docker_data_test-api:
