version: 2
jobs:
  build:
    working_directory: ~/main-ci
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps1-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
      - restore_cache:
          key: deps1-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
      - run:
          name: Install main requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Load cache images
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-api.tar | true
            docker load -i ~/main-ci/caches/images-test-end2end.tar | true
      - run:
          name: Rebuild images
          command: |
            ./$COMMAND_NAME -m test-api rebuild
            ./$COMMAND_NAME -m test-end2end rebuild
      - run:
          name: Save images
          command: |
            mkdir -p ~/main-ci/caches
            docker save $(docker images -q) -o ~/main-ci/caches/images-test-api.tar
            docker save $(docker images -q) -o ~/main-ci/caches/images-test-end2end.tar
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths: ~/main-ci/venv
      - save_cache:
          key: deps1-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/main-ci/caches/images-test-api.tar
      - save_cache:
          key: deps1-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
          paths: ~/main-ci/caches/images-test-end2end.tar

  test-api:
    working_directory: ~/main-ci
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps1-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/main-ci/caches/images-test-api.tar
      - run:
          name: Load test-api cache image
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-api.tar | true
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start test-api
          command: |
            ./$COMMAND_NAME -m test-api start

  test-end2end:
    working_directory: ~/main-ci
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps1-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
          paths: ~/main-ci/caches/images-test-end2end.tar
      - run:
          name: Load test-end2end cache image
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-end2end.tar | true
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start test-end2end
          command: |
            ./$COMMAND_NAME -m test-end2end start

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-api:
          requires:
            - build
      - test-end2end:
          requires:
            - test-api
