version: 2.1

executors:
  classic:
    machine:
      image: circleci/classic:latest
    working_directory: ~/main-ci

commands:
  test:
    parameters:
      key:
        type: string
      mode:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: cache--{{ checksum "requirements.txt" }}
      - restore_cache:
          key: <<parameters.key>>
      - run:
          name: Load <<parameters.mode>> images from cache if exists
          command: |
            set +o pipefail
            if [ -d ~/main-ci/docker-caches/<<parameters.mode>> ]; then
              IMAGE_FILES=$(ls ~/main-ci/docker-caches/<<parameters.mode>>)
              for file in $IMAGE_FILES; do
                docker load -i ~/main-ci/docker-caches/<<parameters.mode>>/$file;
              done
            fi
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start <<parameters.mode>>
          command: |
            ./$COMMAND_NAME -m <<parameters.mode>> start
      - run:
          name: Save <<parameters.mode>> images in caches if not exists
          command: |
            if [ ! -d ~/main-ci/docker-caches/<<parameters.mode>> ]; then
              mkdir -p ~/main-ci/docker-caches/<<parameters.mode>>
              NAMED_IMAGES=$(docker images | awk '{if ($1 != "<none>" && $1 != "REPOSITORY") print $1;}')
              for image in $NAMED_IMAGES; do
                docker save -o ~/main-ci/docker-caches/<<parameters.mode>>/$image.tar $image;
              done
            fi
      - save_cache:
          key: <<parameters.key>>
          paths:
            - ~/main-ci/docker-caches/<<parameters.mode>>

jobs:
  build:
    executor: classic
    steps:
      - checkout
      - restore_cache:
          key: cache--{{ checksum "requirements.txt" }}
      - run:
          name: Install main requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: cache--{{ checksum "requirements.txt" }}
          paths: ~/main-ci/venv
  test-api:
    executor: classic
    steps:
      - test:
          key: cache--{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          mode: "test-api"
  test-end2end:
    executor: classic
    steps:
      - test:
          key: cache--{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
          mode: "test-end2end"


workflows:
  commit:
    jobs:
      - build
      - test-api:
          requires:
            - build
      - test-end2end:
          requires:
            - build
