version: 2.1

executors:
  classic:
    machine:
      image: circleci/classic:latest
    working_directory: ~/main-ci

commands:
  test:
    parameters:
      key:
        type: string
      images:
        type: string
      mode:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: deps16-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: <<parameters.key>>
      - run:
          name: Load <<parameters.mode>> images from cache if exists
          command: |
            set +o pipefail
            docker load -i ~/main-ci/docker-caches/<<parameters.mode>>/images.tar | true
            docker images
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start <<parameters.mode>>
          command: |
            ./$COMMAND_NAME -m <<parameters.mode>> start
      - run:
          name: Save <<parameters.mode>> images in caches
          command: |
            docker images
            if [ ! -d ~/main-ci/docker-caches/<<parameters.mode>> ]; then
              mkdir -p ~/main-ci/docker-caches/<<parameters.mode>>
              docker save -o ~/main-ci/docker-caches/<<parameters.mode>>/images.tar <<parameters.images>>
            fi
      - save_cache:
          key: <<parameters.key>>
          paths:
            - ~/main-ci/docker-caches/<<parameters.mode>>

jobs:
  build:
    executor: classic
    steps:
      - checkout
      - restore_cache:
          key: deps16-{{ checksum "requirements.txt" }}
      - run:
          name: Install main requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: deps16-{{ checksum "requirements.txt" }}
          paths: ~/main-ci/venv
  test-api:
    executor: classic
    steps:
      - test:
          key: deps16-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          images: "mainci_api-test-api postgres"
          mode: "test-api"
  test-end2end:
    executor: classic
    steps:
      - test:
          key: deps16-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
          images: "mainci_api-test-end2end mainci_frontend-test-end2end mainci_nginx-test-end2end postgres"
          mode: "test-end2end"


workflows:
  commit:
    jobs:
      - build
      - test-api:
          requires:
            - build
      - test-end2end:
          requires:
            - build
