version: 2
jobs:
  build-setup:
    working_directory: ~/main-ci
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "requirements.txt" }}
      - run:
          name: Install main requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: deps4-{{ checksum "requirements.txt" }}
          paths: ~/main-ci/venv

  build-test-api:
    working_directory: ~/main-ci
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps4-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
      - run:
          name: Load images from cache if exists
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-api.tar | true
      - run:
          name: Build images
          command: |
            ./$COMMAND_NAME -m test-api build
      - run:
          name: Save images in caches
          command: |
            mkdir -p ~/main-ci/caches
            docker save $(docker images -q) -o ~/main-ci/caches/images-test-api.tar
      - save_cache:
          key: deps4-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/main-ci/caches/images-test-api.tar

    build-test-end2end:
      working_directory: ~/main-ci
      machine:
        image: circleci/classic:latest
      steps:
        - checkout
        - restore_cache:
            key: deps4-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
        - run:
            name: Install main requirements
            command: |
              python -m virtualenv venv
              . venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
        - run:
            name: Load images from cache if exists
            command: |
              set +o pipefail
              docker load -i ~/main-ci/caches/images-test-end2end.tar | true
        - run:
            name: Build images
            command: |
              ./$COMMAND_NAME -m test-api build
              ./$COMMAND_NAME -m test-end2end build
        - run:
            name: Save images in caches
            command: |
              mkdir -p ~/main-ci/caches
              docker save $(docker images -q) -o ~/main-ci/caches/images-test-end2end.tar
        - save_cache:
            key: deps4-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
            paths: ~/main-ci/caches/images-test-end2end.tar

  test-api:
    working_directory: ~/main-ci
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps4-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/main-ci/caches/images-test-api.tar
      - run:
          name: Load test-api image from cache
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-api.tar | true
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start test-api
          command: |
            ./$COMMAND_NAME -m test-api start

  test-end2end:
    working_directory: ~/main-ci
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps4-{{ checksum "docker-compose.test-end2end.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}-{{ checksum "./webapp/package.json"}}
          paths: ~/main-ci/caches/images-test-end2end.tar
      - run:
          name: Load test-end2end image from cache
          command: |
            set +o pipefail
            docker load -i ~/main-ci/caches/images-test-end2end.tar | true
      - run:
          name: Venv
          command: |
            . venv/bin/activate
      - run:
          name: Start test-end2end
          command: |
            ./$COMMAND_NAME -m test-end2end start

workflows:
  version: 2
  commit:
    jobs:
      - build-setup
      - build-test-api:
          requires:
            - build-setup
      - build-test-end2end:
          requires:
            - build-setup
      - test-api:
          requires:
            - build-test-api
      - test-end2end:
          requires:
            - build-test-end2end
