version: 2
jobs:
  build:
    working_directory: ~/main-ci
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: docker-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/caches/images-test-api.tar
      - run:
          name: Install main requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Load test-api cache image
          command: |
            set +o pipefail
            docker load -i ~/caches/images-test-api.tar | true
      - run:
          name: Rebuild test-api image
          command: |
            ./$COMMAND_NAME -m test-api rebuild
      - run:
          name: Save test-api image
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
      - save_cache:
          key: docker-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/caches/images-test-api.tar
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - ~/main-ci/venv

  test-api:
    working_directory: ~/main-ci
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: docker-{{ checksum "docker-compose.test-api.yml" }}-{{ checksum "./api/requirements.txt" }}-{{ checksum "./api/utils/nltk_downloader.py"}}
          paths: ~/caches/images-test-api.tar
      - run:
          name: Load test-api cache image
          command: |
            set +o pipefail
            docker load -i ~/caches/images-test-api.tar | true
      - run:
          name: Running test api
          command: |
            ./$COMMAND_NAME -m test-api start

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-api:
          requires:
            - build
